apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: web-output-keyword
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: web-upload-folder
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 10Gi
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
